services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    shm_size: "1gb"
    volumes:
      - ./dados_exportados:/app/dados_exportados
